# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'YUNmeterDialog.ui'
#
# Created: Sun Oct 15 15:19:32 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(302, 167)
        self.lcd = QtGui.QLCDNumber(Dialog)
        self.lcd.setGeometry(QtCore.QRect(9, 9, 181, 111))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd.sizePolicy().hasHeightForWidth())
        self.lcd.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.lcd.setFont(font)
        self.lcd.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcd.setFrameShadow(QtGui.QFrame.Raised)
        self.lcd.setLineWidth(1)
        self.lcd.setNumDigits(3)
        self.lcd.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd.setProperty("intValue", 0)
        self.lcd.setObjectName("lcd")
        self.radio1 = QtGui.QRadioButton(Dialog)
        self.radio1.setGeometry(QtCore.QRect(202, 75, 48, 22))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio1.sizePolicy().hasHeightForWidth())
        self.radio1.setSizePolicy(sizePolicy)
        self.radio1.setChecked(True)
        self.radio1.setObjectName("radio1")
        self.radio2 = QtGui.QRadioButton(Dialog)
        self.radio2.setGeometry(QtCore.QRect(202, 103, 55, 22))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio2.sizePolicy().hasHeightForWidth())
        self.radio2.setSizePolicy(sizePolicy)
        self.radio2.setObjectName("radio2")
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(9, 131, 64, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.edit1 = QtGui.QLineEdit(Dialog)
        self.edit1.setGeometry(QtCore.QRect(106, 131, 191, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit1.sizePolicy().hasHeightForWidth())
        self.edit1.setSizePolicy(sizePolicy)
        self.edit1.setAlignment(QtCore.Qt.AlignCenter)
        self.edit1.setObjectName("edit1")
        self.btnOK = QtGui.QPushButton(Dialog)
        self.btnOK.setGeometry(QtCore.QRect(202, 9, 85, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOK.sizePolicy().hasHeightForWidth())
        self.btnOK.setSizePolicy(sizePolicy)
        self.btnOK.setObjectName("btnOK")
        self.btnCancel = QtGui.QPushButton(Dialog)
        self.btnCancel.setGeometry(QtCore.QRect(202, 42, 85, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCancel.sizePolicy().hasHeightForWidth())
        self.btnCancel.setSizePolicy(sizePolicy)
        self.btnCancel.setObjectName("btnCancel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "YUNmeter", None, QtGui.QApplication.UnicodeUTF8))
        self.radio1.setText(QtGui.QApplication.translate("Dialog", "cm", None, QtGui.QApplication.UnicodeUTF8))
        self.radio2.setText(QtGui.QApplication.translate("Dialog", "inch", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "IP address:", None, QtGui.QApplication.UnicodeUTF8))
        self.edit1.setText(QtGui.QApplication.translate("Dialog", "arduino.local", None, QtGui.QApplication.UnicodeUTF8))
        self.edit1.setPlaceholderText(QtGui.QApplication.translate("Dialog", "address of Arduino Yun (192.168...)", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOK.setText(QtGui.QApplication.translate("Dialog", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCancel.setText(QtGui.QApplication.translate("Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

